### ISSUE TITLE
failed cookie-op: +dk -o / same process served a 'leaf' bot in +voice chans

### ISSUE THREAD

**Issue by fred0r** [wraith/wraith#127]
Wraith v1.4.8-5335-g94c8f16d
because of a failed cookie-op, one bot got -o and +dk flag - chan was set 'bad-cookie 2' (Kick) .
afterwards the net stopped to voice users in +voice chans, until i removed +dk and did +o on the 'cookie-failed' bot.
that cookie-failed bot is the bot, which connects to the hub and its 'leaf' process was the former 'voice bot' - it wasnt able to connect to the net, which resulted in no autovoice at all.
since my used version should be able to create 'auto-roles' for op/voice: 
why didnt another bot from the net continue to give voice ?

**Comment by bdrewery** [comment]
how many bots do you have in that channel?

**Comment by bdrewery** [comment]
Roles are not negotiated or assigned by the hub. They are decided based on a consistent algorithm they all follow.

This is trivial to reproduce with a botnet split.
hub
`- botA
--`- botB
`- botC

1. Only those 3 bots in the channel.
2. unlink botA and immediately set it +d.
3. wait ~10 seconds
4. Remaining bots will remove botA from any roles and keep botB assigned certain roles.
5. Both botA and botB are delinked and have no idea that the rest of the net considers botA to be +d. So they both still assign roles to botA. Thus it is possible they assign voicing to botA, while the rest of the botnet assigns voicing to botB. Thus no one voices because botB doesn't know it was supposed to voice.

**Comment by fred0r** [comment]
Thank you
